### ISSUE TITLE
OpenGLException: Cannot use offsets when Array Buffer Object is disabled

### ISSUE THREAD

**Issue by tigerss** [libgdx/libgdx-demo-metagun#3]
Running on Linux desktop gives me this error when rendering a sign screen:

```
Exception in thread "LWJGL Application" org.lwjgl.opengl.OpenGLException: Cannot use offsets when Array Buffer Object is disabled
    at org.lwjgl.opengl.GLChecks.ensureArrayVBOenabled(GLChecks.java:77)
    at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:892)
    at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glVertexAttribPointer(LwjglGL20.java:847)
    at com.badlogic.gdx.graphics.glutils.ShaderProgram.setVertexAttribute(ShaderProgram.java:662)
    at com.badlogic.gdx.graphics.glutils.VertexBufferObjectWithVAO.bindAttributes(VertexBufferObjectWithVAO.java:171)
    at com.badlogic.gdx.graphics.glutils.VertexBufferObjectWithVAO.bind(VertexBufferObjectWithVAO.java:147)
    at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:380)
    at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:371)
    at com.badlogic.gdx.graphics.Mesh.render(Mesh.java:479)
    at com.badlogic.gdx.graphics.Mesh.render(Mesh.java:449)
    at com.badlogic.gdx.graphics.g2d.SpriteBatch.flush(SpriteBatch.java:972)
    at com.badlogic.gdx.graphics.g2d.SpriteBatch.end(SpriteBatch.java:180)
    at com.mojang.metagun.screen.GameScreen.render(GameScreen.java:81)
    at com.mojang.metagun.screen.SignReadScreen.render(SignReadScreen.java:44)
    at com.mojang.metagun.Metagun.render(Metagun.java:57)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:214)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

**Comment by xoppa** [comment]
That's because you're using nightly of libgdx (or source). Try to use latest release instead.

**Comment by tigerss** [comment]
Ok, I changed "gdxVersion" to "json.libgdxRelease" in build.gradle, thanks!
